EmployeeManagement/ViewModels/EditRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmployeeManagement.ViewModels
{
    public class EditRoleViewModel
    {
        public string Id { get; set; }
        [Required(ErrorMessage ="Role Name is Required")]
        public string RoleName { get; set; }
        public List<string> users { get; set; }= new List<string>();
    }
}

EmployeeManagement/ViewModels/EditUserViewModel.cs
using System.ComponentModel.DataAnnotations;
using Core.Models;
using EmployeeManagement.Utilites;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.ViewModels
{

    public class EditUserViewModel
    {
        
      public string Id {get;set;}

          [Required]

      public string UserName {get;set;}
        [DataType(DataType.EmailAddress)]
      public string Email {get;set;}


        [Required]
        [DataType(DataType.Password)]
      public string Password {get;set;}
    
      public string City {get;set;}
      public List<string> Claims {get;set;}  =new List<string>();
      public IList<string> Roles {get;set;}= new List<string>();



    
    }
}

EmployeeManagement/Controllers/AdministrationController.cs
using System.Security.Claims;
using Core.Models;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagement.Controllers
{
  //[Authorize(Roles="Admin")]
 //[Authorize(Policy="Admin")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
         private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager
        )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;

        }

    [HttpGet]
  public IActionResult ListUsers()
    {
        var users = _userManager.Users;
        return View(users); 
    }

    [HttpGet]
    public IActionResult CreateRole()
    {
      //  User.Claims.Where(x=>x.Type==ClaimTypes.);
        return View();
    }

    [HttpPost] 
    public async Task<IActionResult> CreateRole(CreateRoleModel model)
    {
        if (ModelState.IsValid)
        {
            IdentityRole identityRole = new IdentityRole
            {
                Name = model.RoleName
            };
            IdentityResult result = await _roleManager.CreateAsync(identityRole);
            if (result.Succeeded)
            {
                return RedirectToAction("index", "Home");
            }

            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

          
        }

        return View(model);
    }

    [HttpGet]
    public IActionResult ListRoles()
    {
        var roles = _roleManager.Roles;
        return View(roles);
    }
    [HttpGet]
    public async Task<IActionResult> EditRole(string id)
    {
        var role = await  _roleManager.FindByIdAsync(id);
        if (role == null)
        {
            ViewBag.ErrorMessage = $"Role with Id ={id} can not founded";
            return View("Notfound");
        }
        var model = new EditRoleViewModel
        {
            Id = role.Id,
            RoleName = role.Name
        };
          foreach (var user in _userManager.Users)
            {
                if(await _userManager.IsInRoleAsync(user,role.Name)){
                     model.users.Add(user.UserName);
                }
            }

        return View(model);

    }
     [HttpPost]
    public async Task<IActionResult> EditRole(EditRoleViewModel model)
    {
        var role = await  _roleManager.FindByIdAsync(model.Id);
        if (role == null)
        {
            ViewBag.ErrorMessage = $"Role with Id ={model.Id} can not founded";
            return View("Notfound");
        }

        role.Name=model.RoleName;
        var result= await _roleManager.UpdateAsync(role);

        if(result.Succeeded){
            return RedirectToAction("ListRoles");
        }
        foreach (var item in result.Errors)
        {
            ModelState.AddModelError("", item.Description);
        }
 await Refresh(User);
        return View(model);

    }

     [HttpGet]
    public async Task<IActionResult> EditUserInRole(string roleId){
        ViewBag.roleId= roleId;
        var role= await _roleManager.FindByIdAsync(roleId);
        if(role==null){
            ViewBag.ErrorMessage=$"Role with Id = {roleId} cannot be found ";
            return View("NotFound"); 
        }
         var model = new List<UserRoleViewModel>();
      
          foreach (var user in _userManager.Users)
            {
                 var userRoleViewModel= new UserRoleViewModel
                 {
                       UserId=user.Id,
                       UserName= user.UserName
                 };

                 if(await _userManager.IsInRoleAsync(user,role.Name)){
                    userRoleViewModel.IsSelected=true;
                 }
                 else{
                    userRoleViewModel.IsSelected=false;
                 }
                 model.Add(userRoleViewModel);
            }

           return View(model);

    }
    [HttpPost]
    public async Task<IActionResult> EditUserInRole(List<UserRoleViewModel> model , string roleId)
    {
          
      var role= await _roleManager.FindByIdAsync(roleId);
        if(role==null){
            ViewBag.ErrorMessage=$"Role with Id = {roleId} cannot be found ";
            return View("NotFound"); 
        }
        for (int i = 0; i < model.Count; i++)
        {
             var user = await _userManager.FindByIdAsync(model[i].UserId);
             IdentityResult result= null;
             if(model[i].IsSelected && !(await _userManager.IsInRoleAsync(user,role.Name))){
                result= await _userManager.AddToRoleAsync(user,role.Name);
                  
             }
             else  if(!model[i].IsSelected && (await _userManager.IsInRoleAsync(user,role.Name))){
                result= await _userManager.RemoveFromRoleAsync(user,role.Name);
                  
             }
             else{
                continue;
             }
             if(result.Succeeded){
                if(i<(model.Count-1)){
                    continue;
                }
                else{
                    return RedirectToAction("EditRole", new {Id=roleId});
                }
             }
        }

         await Refresh(User);

        return RedirectToAction("EditRole", new {Id=roleId});
    
    
    }

 [HttpGet]
    public async Task<IActionResult> EditUser(string userId){
        
        var user= await _userManager.FindByIdAsync(userId);
        if(user==null){
            ViewBag.ErrorMessage=$"Role with Id = {userId} cannot be found ";
            return View("NotFound"); 
        }
        var usersCliams= await _userManager.GetClaimsAsync(user);
        var usersRoles= await _userManager.GetRolesAsync(user);
       var model = new EditUserViewModel
       {
        Id=user.Id ,
        Email=user.Email ,
        UserName=user.UserName,
        City=user.City,     
      //  Claims=  usersCliams.Select(x=>x.Value).ToList(),
        Claims=  usersCliams.Select(x=> x.Type +" : "+ x.Value).ToList(),
        Roles= usersRoles


       };
        await Refresh(User);
           return View(model);

    }
[HttpPost]
    public async Task<IActionResult> EditUser(EditUserViewModel model){
        
        var user= await _userManager.FindByIdAsync(model.Id);
        if(user==null){
            ViewBag.ErrorMessage=$"Role with Id = {model.Id} cannot be found ";
            return View("NotFound"); 
        }
        user.Email= model.Email;
        user.UserName= model.UserName;
        user.City= model.City;
        var result= await _userManager.UpdateAsync(user);
       if(result.Succeeded){
        return RedirectToAction("ListUsers");
       }
       foreach (var item in result.Errors)
       {
        ModelState.AddModelError("", item.Description);
       }

           return View(model);

    }
    
[HttpPost]
  public async Task<IActionResult> DeleteUser(string userId)
  {
     
  var user= await _userManager.FindByIdAsync(userId);
         if(user==null){
            ViewBag.ErrorMessage=$"Role with Id = {userId} cannot be found ";
            return View("NotFound"); 
        }
        try
        {
              var result = await _userManager.DeleteAsync(user);
        if(result.Succeeded){
          return RedirectToAction("ListUsers");
        }
  foreach (var item in result.Errors)
       {
        ModelState.AddModelError("", item.Description);
       }
  return View("ListUsers");
        }
        catch (System.Exception)
        {
            
            ViewBag.ErrorTitle=$"{user.UserName} role is in use "; 
           ViewBag.ErrorMessage=$"{user.UserName} role  can't be delete as there are users  "+
           $"in this role. If you want to delete this role. plz remove the users "; 
         return View("~/Views/Error/Error.cshtml");
        }
      
  }
 

[HttpPost]
[Authorize(Policy ="DeleteRolePolicy")]
  public async Task<IActionResult> DeleteRole(string roleId)
  {  
  var role= await _roleManager.FindByIdAsync(roleId);
         if(role==null){
            ViewBag.ErrorMessage=$"Role with Id = {roleId} cannot be found ";
            return View("NotFound"); 
        }
        try
        {
         var result = await _roleManager.DeleteAsync(role);
         if(result.Succeeded){
          return RedirectToAction("ListRoles");
          }
       foreach (var item in result.Errors)
       {
        ModelState.AddModelError("", item.Description);
       }
        await Refresh(User);
         return View("ListRoles");
        }
        catch (System.Exception)
        {
           ViewBag.ErrorTitle=$"{role.Name} role is in use "; 
           ViewBag.ErrorMessage=$"{role.Name} role  can't be delete as there are users  "+
           $"in this role. If you want to delete this role. plz remove the users "; 
          return View("~/Views/Error/Error.cshtml");
           
        }
     
  }
  

 [HttpGet]
    public async Task<IActionResult> ManageUserRoles(string userId){
        ViewBag.userId=userId;
            var user= await _userManager.FindByIdAsync(userId);
          if(user==null){
            ViewBag.ErrorMessage=$"Role with Id = {userId} cannot be found ";
            return View("NotFound"); 
        }
        var model = new List<UserRolesViewModel>();
        foreach (var role in _roleManager.Roles)
        {
             var userRoleViewModel= new UserRolesViewModel{
                RoleId=role.Id,
                RoleName= role.Name
             };
             if(await _userManager.IsInRoleAsync(user,role.Name)){
                userRoleViewModel.IsSelected=true;

EmployeeManagement/Views/Administration/CreateRole.cshtml
@using EmployeeManagement.ViewModels
@model  CreateRoleModel
@{
    ViewData["Title"] = "Register";
}
<div class="row">
    <div class="col-md-12">
        <form   asp-controller="Administration" asp-action="CreateRole" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">  
                <label asp-for="RoleName" class="control-label"></label>  
                <input asp-for="RoleName" class="form-control" type="text"/>  
                <span asp-validation-for="RoleName" class="text-danger"></span>  
            </div>  
            
            <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Create User" class="btn btn-primary" />  
            </div> 

        </form>
    </div>
</div>

EmployeeManagement/Views/Administration/EditRole.cshtml
@{
    ViewData["Title"] = "EditRole";
}

@using EmployeeManagement.ViewModels
@model  EditRoleViewModel
 
<div class="row">
    <div class="col-md-12">
        <form   asp-controller="Administration" asp-action="EditRole" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">  
                <label asp-for="Id" class="control-label"></label>  
                <input asp-for="Id" readonly disabled class="form-control" type="text"/>  
                <span asp-validation-for="Id" class="text-danger"></span>  
            </div>  
            <div class="form-group">  
                <label asp-for="RoleName" class="control-label"></label>  
                <input asp-for="RoleName" class="form-control" type="text"/>  
                <span asp-validation-for="RoleName" class="text-danger"></span>  
            </div>  
            
            <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Update User" class="btn btn-primary" />  
                         <a asp-controller="Administration" asp-action="ListRoles" class="btn btn-warinig ">Cancel</a>
            </div> 
        <div class="card">
        <div class="card-header">
              users in the Role
        </div>
        <div class="card-body">
            
            @if (Model.users.Any())
            {
                foreach (var user in Model.users)
                {
                 <h5 class="card-tilte">
                    @user
                 </h5>   
                }
                
            }
            else{
                <h5 class="card-title"> Node at the momnet</h5>
            }
            <div class="card-footer">
           <a asp-controller="Administration" asp-action="EditUserInRole" asp-route-roleId="@Model.Id"  class="btn btn-primary">Add Or Remove Users</a>
           @* <a asp-controller="Administration" asp-action="CreateRole" class="btn btn-danger">Remove User</a> *@

            </div>
        </div>
        </div>
        </form>
    </div>
</div>

EmployeeManagement/Views/Administration/EditUser.cshtml
@{
    ViewData["Title"] = "EditUser";
}
@model EditUserViewModel


<div class="row">
    <div class="col-md-12">
        <form   asp-controller="Administration" asp-action="EditUser" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">  
                <label asp-for="Id" class="control-label"></label>  
                <input asp-for="Id" readonly disabled class="form-control" type="text"/>  
                <span asp-validation-for="Id" class="text-danger"></span>  
            </div> 
              <div class="form-group">  
                <label asp-for="UserName" class="control-label"></label>  
                <input asp-for="UserName" class="form-control" type="text"/>  
                <span asp-validation-for="UserName" class="text-danger"></span>  
            </div> 

            <div class="form-group">  
                <label asp-for="Email" class="control-label"></label>  
                <input asp-for="Email" class="form-control" type="text"/>  
                <span asp-validation-for="Email" class="text-danger"></span>  
            </div> 
            <div class="form-group">  
                <label asp-for="City" class="control-label"></label>  
                <input asp-for="City" class="form-control" type="text"/>  
                <span asp-validation-for="City" class="text-danger"></span>  
            </div> 
            
            <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Update User" class="btn btn-primary" />  
                         <a asp-controller="Administration" asp-action="ListRoles" class="btn btn-warinig ">Cancel</a>
            </div> 
        <div class="card">
        <div class="card-header">
              users in the Role
        </div>
        <div class="card-body">
            
            @if (Model.Roles.Any())
            {
                foreach (var user in Model.Roles)
                {
                 <h5 class="card-tilte">
                    @user
                 </h5>   
                }
            }
            else{
                <h5 class="card-title"> Node at the momnet</h5>
            }
             <div class="card-footer">
           <a asp-controller="Administration" asp-action="ManageUserRoles" asp-route-userId="@Model.Id"
             class="btn btn-primary">Manage Users Roles</a>
                  </div>
        </div>
        </div>

         <div class="card">
        <div class="card-header">
              users in the Claims
        </div>
        <div class="card-body">
            
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                 <h5 class="card-tilte">
                    @claim
                 </h5>   
                }
                
            }
            else{
                <h5 class="card-title"> Node at the momnet</h5>
            }
                  <div class="card-footer">
           <a asp-controller="Administration" asp-action="ManageUserClaims" asp-route-userId="@Model.Id"
             class="btn btn-primary">Manage User Claims</a>
                  </div>
        </div>
        </div>
        </form>
    </div>
</div>

EmployeeManagement/Views/Administration/EditUserInRole.cshtml
@model List<UserRoleViewModel>
@{
    ViewData["Title"] = "EditUserInRole";
     var roleId= ViewBag.roleId;
     
}

<form   asp-controller="Administration" asp-action="EditUserInRole"  method="post">
    <div class="card">
        <div class="card-header">
     <input type="hidden"  id="roleId" name="roleId" class="form-control" value=@roleId >
        </div>
        <div class="card-body">
          @for (int i = 0; i < Model.Count; i++)
          {
              <div class="form-check m-1">
                 
                  <input type="hidden" asp-for="@Model[i].UserId" class="form-check-input">
                  <input  type="hidden" asp-for="@Model[i].UserName" class="form-check-input">
                
                  <input asp-for="@Model[i].IsSelected" class="form-check-input">
                  <label class="form-check-label" asp-for="@Model[i].IsSelected">
                    @Model[i].UserName
                  </label>
              </div>
          }
        </div>
        <div class="card- footer">
           
     
        </div>
           
    </div>
    <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Update" class="btn btn-primary" />  
                        <a asp-controller="Administration" asp-action="EditRole" 
                         class="btn btn-danger ">Cancel</a>

            </div> 
</form>

EmployeeManagement/Views/Administration/ListRoles.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Authorization
@model   IEnumerable<IdentityRole>; 
@inject  IAuthorizationService  _authorizationService    
@{
    ViewData["Title"] = "ListRoles";
}
  <a asp-controller="Administration" asp-action="CreateRole"  class="btn btn-primary">Add new role</a>
     
@if(Model.Any()){
  foreach (var item in Model)
  {
     <div class="card">
        <div class="card-header">
             Role Id : @item.Id
        </div>
        <div class="card-body">
            <h5 class="card-title">
                @item.Name
            </h5>
<form method="post" asp-controller="Administration" asp-action="DeleteRole"  asp-route-roleId="@item.Id" >
    @if((await _authorizationService.AuthorizeAsync(User,"EditRolePolicy")).Succeeded){
 <a asp-controller="Administration" asp-action="EditRole" asp-route-Id="@item.Id"
          class="btn btn-primary ">edit</a>
    }
        
          
          

           <span id="confirDeleteSpan_@item.Id" style="display: none;">
            <span>Are You sure you want to delete ?</span>
             <button type="submit" class="btn btn-danger" 
           onclick="confirmDelete('@item.Id',false) "
           >yes</button>
           <a href="" class="btn btn-primary">No</a>
           </span>
           <span id="DeleteSpan_@item.Id">
            <a href="#" class="btn btn-danger"
             onclick="confirmDelete('@item.Id',true) ">Delete</a>
           </span>
        </form>
        </div>
    </div>
  }
}
else{
    <div class="card">
        <div class="card-header">
            No Roles Created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a role 
            </h5>
           <a asp-controller="Administration" asp-action="CreateRole" class="btn btn-warinig ">Create Role</a>
        </div>
    </div>
}

   
    @section scripts{
        <script src="~/js/Custom.js"></script>   
    }

EmployeeManagement/Views/Administration/ListUsers.cshtml
@{
    ViewData["Title"] = "ListUsers";
}
@model IEnumerable<ApplicationUser>

    <h1>All Users </h1>

    @if(Model.Any()){
        foreach (var item in Model)
        {
           <div class="card">
        <div class="card-header">
             User Id : @item.Id
        </div>
        <div class="card-body">
            <h5 class="card-title">
                @item.UserName
            </h5>
        <form method="post" asp-controller="Administration" asp-action="DeleteUser"  asp-route-userId="@item.Id" >
         <a asp-controller="Administration" asp-action="EditUser" asp-route-userId="@item.Id"
          class="btn btn-primary ">edit</a>
          
          

           <span id="confirDeleteSpan_@item.Id" style="display: none;">
            <span>Are You sure you want to delete ?</span>
            <button type="submit" class="btn btn-danger" >yes</button>
           <a href="" class="btn btn-primary"  onclick="confirmDelete('@item.Id',false)">No</a>
           </span>
           <span id="DeleteSpan_@item.Id">
            <a href="#" class="btn btn-danger"
             onclick="confirmDelete('@item.Id',true) ">Delete</a>
           </span>
        </form>
         
        </div>
    </div> 
        }
 

    }
    
    @section scripts{
        <script src="~/js/Custom.js"></script>   
    }

EmployeeManagement/Views/Administration/ManageUserClaims.cshtml
@{
    ViewData["Title"] = "ManageUserClaims";
}
@model UserClaimsViewModel;

<form   asp-controller="Administration" asp-action="ManageUserClaims"  method="post">
    <div class="card">
        <div class="card-header">
         <input type="hidden" asp-for="@Model.userId" class="form-check-input">

     <h2>Manage Users Claims</h2>
        </div>
        <div class="card-body">
          @for (int i = 0; i < Model.Claims.Count; i++)
          {
              <div class="form-check m-1">
                 
                  <input type="hidden" asp-for="@Model.Claims[i].ClaimType" class="form-check-input">
                   
                  <input asp-for="@Model.Claims[i].IsSelected" class="form-check-input">
                  <label class="form-check-label" asp-for="@Model.Claims[i].IsSelected">
                    @Model.Claims[i].ClaimType
                  </label>
              </div>
          }
                   <div asp-validation-summary="All" class="text-danger"></div>
            
        </div>
        <div class="card- footer">
           
     
        </div>
           
    </div>
    <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Update" class="btn btn-primary" />  
                        <a asp-controller="Administration" asp-action="EditUser" 
                         class="btn btn-danger ">Cancel</a>

            </div> 
</form>

EmployeeManagement/Views/Administration/ManageUserRoles.cshtml
@model List<UserRolesViewModel>
@{
    ViewData["Title"] = "ManageUserRoles";
    var userId=  ViewBag.userId;
}

<form   asp-controller="Administration" asp-action="ManageUserRoles"  method="post">
    <div class="card">
        <div class="card-header">
     <input type="hidden"  id="userId" name="userId" class="form-control" value=@userId >
        </div>
        <div class="card-body">
          @for (int i = 0; i < Model.Count; i++)
          {
              <div class="form-check m-1">
                 
                  <input type="hidden" asp-for="@Model[i].RoleId" class="form-check-input">
                  <input  type="hidden" asp-for="@Model[i].RoleName" class="form-check-input">
                
                  <input asp-for="@Model[i].IsSelected" class="form-check-input">
                  <label class="form-check-label" asp-for="@Model[i].IsSelected">
                    @Model[i].RoleName
                  </label>
              </div>
          }
        </div>
        <div class="card- footer">
           
     
        </div>
           
    </div>
    <div class="form-group " style="margin-top: 30px;" >  
                        <input type="submit" value="Update" class="btn btn-primary" />  
                        <a asp-controller="Administration" asp-action="EditUser" 
                         class="btn btn-danger ">Cancel</a>

            </div> 
</form>